### Add Custom nginx file to web container for http password access
###  create htpasswd file by tunning the command -- htpasswd -c ivre-opt/.htpasswd pscanner
FROM ivre/web
COPY ivre-opt/nginx.conf /etc/nginx/nginx.conf